# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: Validate-Terraform-init-plan-apply.yml

on:
  workflow_dispatch:
    inputs:
      run_apply:
        required: true
        description: Whether or not to run Terraform apply
        type: boolean
        default: false
      run_destroy:
        required: true
        description: Whether or not to run Terraform destroy
        type: boolean
        default: false  
  pull_request:
    paths:
      - '.github/workflow/terraform.yml'
    branches:
      - main
  push:
    paths:
      - '.github/workflow/terraform.yml'
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} # abraham token

jobs:
  run_tf_fmt_check:
    name: Terraform fmt check
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-time.outputs.name }}
      output2: ${{ steps.end-time.outputs.name }}
      output3: ${{ steps.branch.outputs.name }}

    steps:
    - name: get start time
      id: set-time
      run: |
        date +%s%3N
        #echo -e "::set-output name=start-time::$(date +%s%3N)"
        echo "name=start-time::$(date +%s%3N)" >> "$GITHUB_OUTPUT"

    - name: get end time
      id: end-time
      run: |
        date +%s%3N
        echo "name=end-time::$(date +%s%3N)" >> "$GITHUB_OUTPUT"  

    - name: Get time value
      run: echo "${{ steps.set-time.outputs.name }}"  

    - name: Get end time value
      run: echo "${{ steps.end-time.outputs.name }}" 

    - name: Set Repo branch
      id: branch
      run: |
          #plan -out="$outfile"
        #echo "REPO_NAME=$outfile" >> "$GITHUB_OUTPUT"
        echo "name=REPO_NAME::$(echo ${GITHUB_REPOSITORY} | sed 's@.*/@@')" >> "$GITHUB_OUTPUT"
        echo "${{ steps.branch.outputs.name }}"
    - name: Echo repo name
      run: echo "${{ steps.branch.outputs.name }}"       

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  

    - name: Terraform Format
      run: terraform fmt -check -recursive

  my_outputs:
    runs-on: ubuntu-latest
    needs: run_tf_fmt_check
    steps:
      - env:
          OUTPUT1: ${{needs.run_tf_fmt_check.outputs.output1}}
          OUTPUT2: ${{needs.run_tf_fmt_check.outputs.output2}}
          OUTPUT3: ${{needs.run_tf_fmt_check.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"    

  run_tf_init_plan:
    name: Terraform init and plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

  run_apply_destroy:
    name: Terraform apply and destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      #if: github.workflow_dispatch == true
      if: inputs.run_apply == true
      run: terraform apply -auto-approve -input=false

    - name: TF state pull
      run: terraform state pull  

    - name: TF workspace 
      run: terraform workspace show  

    - name: TF Destroy
      if: inputs.run_destroy == true
      run: terraform destroy -auto-approve -input=false
